# This YAML file describes your package. Stack will automatically generate a
# Cabal file when you run `stack build`. See the hpack website for help with
# this file: <https://github.com/sol/hpack>.
benchmarks:
  funnyprint-benchmarks:
    dependencies:
    - base
    - funnyprint
    - criterion
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: benchmark
category: Other
description: funnyprint is a new Haskeleton package.
executables:
  funnyprint:
    dependencies:
    - base
    - funnyprint
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: executable
extra-source-files:
- CHANGELOG.md
- LICENSE.md
- package.yaml
- README.md
- stack.yaml
ghc-options: -Wall
github: Pitometsu/funnyprint
library:
  dependencies:
  - base
  source-dirs: library
license: MIT
maintainer: Yuriy Pitomets
name: funnyprint
synopsis: A new Haskeleton package.
tests:
  funnyprint-test-suite:
    dependencies:
    - base
    - funnyprint
    - tasty
    - tasty-hspec
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: test-suite
version: '0.0.0'
