# This YAML file describes your package. Stack will automatically generate a
# Cabal file when you run `stack build`. See the hpack website for help with
# this file: <https://github.com/sol/hpack>.
benchmarks:
  funnyprint-benchmarks:
    dependencies:
    - base >= 2 && < 6
    - hscolour
    - ipprint == 0.6
    - funnyprint
    - criterion
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: benchmark
category: Text
description: see FunnyPrint.funnyPrint.
extra-source-files:
- CHANGELOG.md
- LICENSE.md
- package.yaml
- README.md
- stack.yaml
ghc-options: -Wall
github: Pitometsu/funnyprint
library:
  dependencies:
  - base >= 2 && < 6
  - hscolour
  - ipprint == 0.6
  source-dirs: library
license: MIT
license-file: LICENSE.md
maintainer: Yuriy Pitomets
name: funnyprint
synopsis: funnyPrint function to colorize GHCi output.
tests:
  funnyprint-test-suite:
    dependencies:
    - base >= 2 && < 6
    - hscolour
    - ipprint == 0.6
    - funnyprint
    - tasty
    - tasty-hspec
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: test-suite
version: '0.0.2'
